a=int(input("Enter your first number: "))
b=int(input("Enter your second number: "))
print("")
print("Addition: ",a+b)
print("Substraction: ",a-b)
print("Division: ",a/b)
print("Multiplication: ",a*b)
print("Division: ",a/b)
print("Integer division: ",a//b)
print("Reminder: ",a%b)